internshipproject/internshipproject/urls.py
from django.contrib import admin
from django.urls import path
import internshipapp.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', internshipapp.views.home, name='home'),
    path('list/', internshipapp.views.list_data, name='list'),
    path('add_structure/', internshipapp.views.add_structure, name='add_structure'),
    path('add_supervisor/', internshipapp.views.add_supervisor, name='add_supervisor'),
    path('add_internship/', internshipapp.views.add_internship, name='add_internship'),
    path('view_structure/<int:structure_id>/', internshipapp.views.view_structure, name='view_structure'),
    path('view_supervisor/<int:supervisor_id>/', internshipapp.views.view_supervisor, name='view_supervisor'),
    path('view_internship/<int:internship_id>/', internshipapp.views.view_internship, name='view_internship'),
    path('edit_structure/<int:structure_id>/', internshipapp.views.edit_structure, name='edit_structure'),
    path('edit_supervisor/<int:supervisor_id>/', internshipapp.views.edit_supervisor, name='edit_supervisor'),
    path('edit_internship/<int:internship_id>/', internshipapp.views.edit_internship, name='edit_internship'),
    path('delete_structure/<int:structure_id>/', internshipapp.views.delete_structure, name='delete_structure'),
    path('delete_supervisor/<int:supervisor_id>/', internshipapp.views.delete_supervisor, name='delete_supervisor'),
    path('delete_internship/<int:internship_id>/', internshipapp.views.delete_internship, name='delete_internship'),
]

internshipproject/internshipapp/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
import geocoder


mapbox_access_token = 'pk.eyJ1IjoicmFwaGJucmQiLCJhIjoiY2t6b2JxY3kzMDBkaTJ2bGdrZGh0eWw1YiJ9.2NQdKAVg0_LKbqxqwMKAIA'

class Structure(models.Model):

    class StructureType(models.TextChoices):
        REASEARCH = 'RE'
        COMPANY = 'CO'
        ASSOCIATION = 'AS'
        PUBLIC = 'PU'
        START_UP = 'ST'
        OTHER = 'OT'
        UNKNOWN = 'UN'
    
    name = models.fields.CharField(max_length=400)
    location_lat = models.fields.FloatField(
        validators=[MinValueValidator(-90), MaxValueValidator(90)], null=True, blank=True
        )
    location_lon = models.fields.FloatField(
        validators=[MinValueValidator(-180), MaxValueValidator(180)], null=True, blank=True
        )
    address = models.fields.CharField(max_length=200)
    city = models.fields.CharField(max_length=100)
    state = models.fields.CharField(max_length=100)
    webpage = models.fields.URLField(null=True, blank=True)
    type = models.fields.CharField(choices=StructureType.choices, max_length=5,
                                    default='UN', null=True, blank=True)
    contact = models.fields.CharField(max_length=500, null=True, blank=True)
    comment = models.fields.CharField(max_length=1000, null=True, blank=True)

    def save(self, *args, **kwargs):
        g = geocoder.mapbox(self.address, key=mapbox_access_token)
        lat_lon = g.latlng  # (lat, long)
        city_g = g.city
        country_g = g.country
        self.location_lat = lat_lon[0]
        self.location_lon = lat_lon[1]
        self.city = city_g
        self.state = country_g
        return super(Structure, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

class Supervisor(models.Model):
    name = models.fields.CharField(max_length=200)
    domain = models.fields.CharField(max_length=200, null=True, blank=True)
    webpage = models.fields.URLField(null=True, blank=True)
    contact = models.fields.CharField(max_length=500, null=True, blank=True)
    comment = models.fields.CharField(max_length=1000, null=True, blank=True)

    structure = models.ForeignKey(Structure, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f'{self.name}'

class Internship(models.Model):

    class InternshipProgress(models.TextChoices):
        NOT_CONTACTED = '09NC'
        FIRST_CONTACT_SENT = '08FCS'
        NEGATIVE_RESPONSE = '10NEG'
        PREPARE_INTERVIEW = '07PRITW'
        INTERVIEW_DONE = '06ITWD'
        ACCEPTED = '05ACC'
        CHOSEN_INTERNSHIP = '04CHINT'
        ADMINISTRATIVE_PROCEDURE = '03ADMIN'
        WAITING_FOR_BEGINING = '02WAITB'
        INTERNSHIP = '01INT'
        FINISHED_INTERNSHIP = '00FIN'

    title = models.fields.CharField(max_length=500)
    description = models.fields.CharField(max_length=2000, null=True, blank=True)
    webpage = models.fields.URLField(null=True, blank=True)
    contact = models.fields.CharField(max_length=500, null=True, blank=True)
    comment = models.fields.CharField(max_length=1000, null=True, blank=True)
    positive_points = models.fields.CharField(max_length=1000, null=True, blank=True)
    negative_points = models.fields.CharField(max_length=1000, null=True, blank=True)
    progress = models.fields.CharField(choices=InternshipProgress.choices, max_length=15,
                                    default='09NC', null=True, blank=True)
    
    structure = models.ForeignKey(Structure, null=True, on_delete=models.SET_NULL)
    supervisor = models.ForeignKey(Supervisor, null=True, on_delete=models.SET_NULL)

internshipproject/internshipapp/forms.py
from django import forms

from . import models

class StructureForm(forms.ModelForm):
    class Meta:
        model = models.Structure
        exclude = ('location_lat', 'location_lon', 'city', 'state' )

class SupervisorForm(forms.ModelForm):
    class Meta:
        model = models.Supervisor
        fields = '__all__'

class InternshipForm(forms.ModelForm):
    class Meta:
        model = models.Internship
        fields = '__all__'
    

internshipproject/internshipapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from numpy import mean

from . import models, forms


def home(request):
    mapbox_access_token = 'pk.eyJ1IjoicmFwaGJucmQiLCJhIjoiY2t6b2JxY3kzMDBkaTJ2bGdrZGh0eWw1YiJ9.2NQdKAVg0_LKbqxqwMKAIA'
    structures = models.Structure.objects.order_by("-location_lat")
    # define initial view of the map
    ini_zoom = 0.001
    mean_lon, mean_lat = 0, 0
    if len(structures)>0:
        loc_lons = [structure.location_lon for structure in structures]
        loc_lats = [structure.location_lat for structure in structures]
        mean_lon = mean(loc_lons)
        mean_lat = mean(loc_lats)
        range_lons = max(loc_lons)- min(loc_lons)
        range_lats = max(loc_lats) - min(loc_lats)
        range_lonlat_lim_zoom = [ [(130,40), 2],
                                [(35,10), 4],
                                [(10,3), 6],
                                [(1,0.5), 8] ]    # limit range lon-lat associated to a zoom
        for ele in range_lonlat_lim_zoom:
            if 2*range_lons<ele[0][0] and 2*range_lats<ele[0][1]:   # 2 factor for security
                ini_zoom = ele[1]
            else:
                break
    return render(request, 'internshipapp/home.html',
                  context={'structures':structures,
                           'mapbox_access_token':mapbox_access_token,
                           'mean_lon':mean_lon,
                           'mean_lat':mean_lat,
                           'ini_zoom':ini_zoom})


def list_data(request):
    structures = models.Structure.objects.all()
    supervisors = models.Supervisor.objects.all()
    internships = models.Internship.objects.order_by("progress")
    return render(request, 'internshipapp/list_data.html',
                  context={'structures':structures,
                           'supervisors':supervisors,
                           'internships':internships})


def add_structure(request):
    structure_form = forms.StructureForm()
    if request.method== 'POST':
        structure_form = forms.StructureForm(request.POST)
        if structure_form.is_valid():
            structure = structure_form.save(commit=False)
            structure.save()
            return redirect('home')
    return render(request, 'internshipapp/add_structure.html',
                  context={'structure_form':structure_form})


def add_supervisor(request):
    supervisor_form = forms.SupervisorForm()
    if request.method== 'POST':
        supervisor_form = forms.SupervisorForm(request.POST)
        if supervisor_form.is_valid():
            supervisor = supervisor_form.save(commit=False)
            supervisor.save()
            return redirect('home')
    return render(request, 'internshipapp/add_supervisor.html',
                  context={'supervisor_form':supervisor_form})


def add_internship(request):
    internship_form = forms.InternshipForm()
    if request.method== 'POST':
        internship_form = forms.InternshipForm(request.POST)
        if internship_form.is_valid():
            internship = internship_form.save(commit=False)
            internship.save()
            return redirect('home')
    return render(request, 'internshipapp/add_internship.html',
                  context={'internship_form':internship_form})

def view_structure(request, structure_id):
    structure_chosen = get_object_or_404(models.Structure, id=structure_id)
    mapbox_access_token = 'pk.eyJ1IjoicmFwaGJucmQiLCJhIjoiY2t6b2JxY3kzMDBkaTJ2bGdrZGh0eWw1YiJ9.2NQdKAVg0_LKbqxqwMKAIA'
    structures = models.Structure.objects.order_by("-location_lat")
    return render(request, 'internshipapp/view_structure.html',
                  context={'structure_chosen':structure_chosen,
                           'structures':structures,
                           'mapbox_access_token':mapbox_access_token})

def view_supervisor(request, supervisor_id):
    supervisor = get_object_or_404(models.Supervisor, id=supervisor_id)
    mapbox_access_token = 'pk.eyJ1IjoicmFwaGJucmQiLCJhIjoiY2t6b2JxY3kzMDBkaTJ2bGdrZGh0eWw1YiJ9.2NQdKAVg0_LKbqxqwMKAIA'
    structures = models.Structure.objects.order_by("-location_lat")
    return render(request, 'internshipapp/view_supervisor.html',
                  context={'supervisor':supervisor,
                           'structures':structures,
                           'mapbox_access_token':mapbox_access_token})

def view_internship(request, internship_id):
    internship = get_object_or_404(models.Internship, id=internship_id)
    mapbox_access_token = 'pk.eyJ1IjoicmFwaGJucmQiLCJhIjoiY2t6b2JxY3kzMDBkaTJ2bGdrZGh0eWw1YiJ9.2NQdKAVg0_LKbqxqwMKAIA'
    structures = models.Structure.objects.order_by("-location_lat")
    return render(request, 'internshipapp/view_internship.html',
                  context={'internship':internship,
                           'structures':structures,
                           'mapbox_access_token':mapbox_access_token})

def edit_structure(request, structure_id):
    structure = get_object_or_404(models.Structure, id=structure_id)
    if request.method == 'POST':
        form = forms.StructureForm(request.POST, instance=structure)
        if form.is_valid():
            form.save()
            return redirect('view_structure', structure_id)
    else:
        form = forms.StructureForm(instance=structure)
    return render(request, 'internshipapp/edit_structure.html',
            context={'structure' : structure, 'form' : form})

def edit_supervisor(request, supervisor_id):
    supervisor = get_object_or_404(models.Supervisor, id=supervisor_id)
    if request.method == 'POST':
        form = forms.SupervisorForm(request.POST, instance=supervisor)
        if form.is_valid():
            form.save()
            return redirect('view_supervisor', supervisor_id)
    else:
        form = forms.SupervisorForm(instance=supervisor)
    return render(request, 'internshipapp/edit_supervisor.html',
            context={'supervisor' : supervisor, 'form' : form})

def edit_internship(request, internship_id):
    internship = get_object_or_404(models.Internship, id=internship_id)
    if request.method == 'POST':
        form = forms.InternshipForm(request.POST, instance=internship)
        if form.is_valid():
            form.save()
            return redirect('view_internship', internship_id)
    else:
        form = forms.InternshipForm(instance=internship)
    return render(request, 'internshipapp/edit_internship.html',
            context={'internship' : internship, 'form' : form})


def delete_structure(request, structure_id):
    structure = models.Structure.objects.get(id=structure_id)
    if request.method == 'POST':
        structure.delete()
        return redirect('home')
    return render(request, 'internshipapp/delete_structure.html',
            context={'structure' : structure})


def delete_supervisor(request, supervisor_id):
    supervisor = models.Supervisor.objects.get(id=supervisor_id)
    if request.method == 'POST':
        supervisor.delete()
        return redirect('home')
    return render(request, 'internshipapp/delete_supervisor.html',
            context={'supervisor' : supervisor})


def delete_internship(request, internship_id):
    internship = models.Internship.objects.get(id=internship_id)
    if request.method == 'POST':
        internship.delete()
        return redirect('home')
    return render(request, 'internshipapp/delete_internship.html',
            context={'internship' : internship})

internshipproject/internshipapp/templates/internshipapp/home.html
{% extends 'base.html' %}
{% block content %}

    <h2>Carte des stages</h2>
    
    <!--Marker hover reactivity-->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script>
    <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css" rel="stylesheet" />
    <style>
        /* Change the cursor to a pointer on hover so the user knows it's clickable */
        .mapboxgl-marker:hover { cursor: pointer; }
        /* darken the marker on hover */
        .mapboxgl-marker:hover svg > g > g:nth-child(2) { fill: #6ea76b; }
    </style>

    <!--Display the map-->
    <div id='map' style='width: 90%; height: 80%;'></div>
    <script>
        mapboxgl.accessToken = '{{ mapbox_access_token }}';
        const map = new mapboxgl.Map({
            container: 'map', // container ID
            style: 'mapbox://styles/mapbox/streets-v11', // style URL
            center: ['{{mean_lon}}', '{{mean_lat}}'], // starting position [lng, lat]
            zoom: '{{ini_zoom}}' // starting zoom
        });
        map.addControl(new mapboxgl.NavigationControl());
    </script>
    
    <!--Display markers on the map-->
    {% for structure in structures %}
    <script>
        new mapboxgl.Marker({ "color": "#23aa1b" })
            .setLngLat(['{{structure.location_lon}}', '{{structure.location_lat}}'])
            .setPopup(
                new mapboxgl.Popup({ "anchor": "bottom-left" })
                    .setHTML("<h4><a href='{% url 'view_structure' structure.id %}' style='color: #177112'>{{ structure.name }}</a></h4>{% for internship in structure.internship_set.all %}<p><a href='{% url 'view_internship' internship.id %}' style='color: #23aa1b'>{{ internship.title }}</a></p>{% endfor %}")
            )
            .addTo(map);
    </script>
    {% endfor %}

    <style>
        .mapboxgl-popup-content{background-color: #c3e6c1;}
        .mapboxgl-popup-anchor-bottom-left > .mapboxgl-popup-tip { border-top-color: #c3e6c1;}
    </style>

{% endblock content %}

internshipproject/internshipapp/templates/internshipapp/list_data.html
{% extends 'base.html' %}
{% block content %}

<style>
    .ligne {text-align: start; padding:2 5 5 5px; color: #3c6d39; background-color: #9ce098;}
    .internship {width:300px; color: #9ce098; background-color: #3c6d39;}
    .supervisor {width:30px; color: #9ce098; background-color: #3c6d39;}
    .structure {width:30px; color: #9ce098; background-color: #3c6d39;}
    .progress {width:30px; color: #9ce098; background-color: #3c6d39;}
    .city {width:30px; color: #9ce098; background-color: #3c6d39;}
    .type {width:30px; color: #9ce098; background-color: #3c6d39;}
    .domain {width:30px; color: #9ce098; background-color: #3c6d39;}
</style>
    
    <h2>Liste des informations des stages</h2>
    
    <table width="90%" border="1" style='border-collapse: collapse;'>
        <thead>
            <tr>
                <th class="internship">Stage</th>
                <th class="supervisor">Tuteur·ice</th>
                <th class="structure">Structure</th>
                <th class="progress">Avancement</th>
            </tr>
        </thead>
        <tbody>
            <tr>{% for internship in internships %}
                    <th class="ligne"><a href="{% url 'view_internship' internship.id %}">{{ internship.title }}</a></th>
                    <th class="ligne">{% if internship.supervisor %}<a href="{% url 'view_supervisor' internship.supervisor.id %}">{{ internship.supervisor.name }}</a>{% endif %}</th>
                    <th class="ligne">{% if internship.structure %}<a href="{% url 'view_structure' internship.structure.id %}">{{ internship.structure.name }}</a>{% endif %}</th>
                    <th class="ligne">{{ internship.get_progress_display }}</a></th>
            </tr>{% endfor %}
        </tbody>
    </table>

    <br><br>
    
    
    <h2>Liste des informations des structures</h2>
    
    <table width="90%" border="1" style='border-collapse: collapse;'>
        <thead>
            <tr>
                <th class="structure">Structure</th>
                <th class="city">Ville</th>
                <th class="type">Type</th>
            </tr>
        </thead>
        <tbody>
            <tr>{% for structure in structures %}
                <th class="ligne"><a href="{% url 'view_structure' structure.id %}">{{ structure.name }}</a></th>
                <th class="ligne">{{ structure.city }}</th>
                <th class="ligne">{{ structure.get_type_display }}</th>
            </tr>{% endfor %}
        </tbody>
    </table>

    <br><br>
    
    
    <h2>Liste des informations des tuteur·ice·s</h2>
    
    <table width="90%" border="1" style='border-collapse: collapse;'>
        <thead>
            <tr>
                <th class="supervisor">Tuteur·ice</th>
                <th class="structure">Structure</th>
                <th class="domain">Domaine</th>
            </tr>
        </thead>
        <tbody>
            <tr>{% for supervisor in supervisors %}
                <th class="ligne"><a href="{% url 'view_supervisor' supervisor.id %}">{{ supervisor.name }}</a></th>
                <th class="ligne">{% if supervisor.structure %}<a href="{% url 'view_structure' supervisor.structure.id %}">{{ supervisor.structure.name }}</a>{% endif %}</th>
                <th class="ligne">{{ supervisor.domain }}</th>
            </tr>{% endfor %}
        </tbody>
    </table>

{% endblock content %}

internshipproject/internshipapp/templates/internshipapp/view_internship.html
{% extends 'base.html' %}
{% block content %}

    <h2>STAGE</h2>
    <h3>{{ internship.title }}</h3>
    
    <ul>
            <li>Description : {{ internship.description|default_if_none:"" }}</li>
        {% if internship.webpage %}
            <li>Lien : <a href="{{ internship.webpage }}">{{ internship.webpage }}</a></li>
        {% endif %}
        {% if internship.contact %}
            <li>Contact (e-mail/téléphone) : {{ internship.contact }}</li>
        {% endif %}
        {% if internship.comment %}
            <li>Commentaire : {{ internship.comment }}</li>
        {% endif %}  
        {% if internship.positive_points or internship.negative_points %}
            <li>Points positifs : {{ internship.positive_points|default_if_none:"" }}</li>
            <li>Points négatifs : {{ internship.negative_points|default_if_none:"" }}</li>
        {% endif %} 
        <br>
        {% if internship.structure %}
            <li>Structure : <a href="{% url 'view_structure' internship.structure.id %}">{{ internship.structure }}</a></li>
            {% if internship.structure.type %}
                <li>Type de structure : {{ internship.structure.get_type_display }}</li>
            {% endif %} 
            <li>Ville - Pays : {{ internship.structure.city }} - {{ internship.structure.state }}</li>
        {% endif %}
        <br>
        {% if internship.supervisor %}
            <li>Tuteur·ice : <a href="{% url 'view_supervisor' internship.supervisor.id %}">{{ internship.supervisor }}</a></li>
        {% endif %}
        <br>
        {% if internship.progress %}
            <li>Avancement dans la demande de stage : {{ internship.get_progress_display }}</a></li>
        {% endif %}
    </ul>

    <a href="{% url 'edit_internship' internship.id %}">Modifier les infos du stage</a>
    <a href="{% url 'delete_internship' internship.id %}">Supprimer le stage</a>

    <br><br><br>

    <!--_________MAP_________-->
    {% if internship.structure %}
    <!--Marker hover reactivity-->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script>
    <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css" rel="stylesheet" />
    <style>
        /* Change the cursor to a pointer on hover so the user knows it's clickable */
        .mapboxgl-marker:hover { cursor: pointer; }
        /* darken the marker on hover */
        .mapboxgl-marker:hover svg > g > g:nth-child(2) { fill: #6ea76b; }
    </style>

    <!--Display the map-->
    <div id='map' style='width: 40%; height: 40%;'></div>
    <script>
        mapboxgl.accessToken = '{{ mapbox_access_token }}';
        const map = new mapboxgl.Map({
            container: 'map', // container ID
            style: 'mapbox://styles/mapbox/streets-v11', // style URL
            center: ['{{internship.structure.location_lon}}', '{{internship.structure.location_lat}}'], // starting position [lng, lat]
            zoom: 5 // starting zoom
        });
        map.addControl(new mapboxgl.NavigationControl());
    </script>
    
    <!--Display markers on the map-->
    {% for structure in structures %}
    {% if structure != internship.structure %}
    <script>
        new mapboxgl.Marker({ "color": "#23aa1b" })
            .setLngLat(['{{structure.location_lon}}', '{{structure.location_lat}}'])
            .setPopup(
                new mapboxgl.Popup({ "anchor": "bottom-left" })
                    .setHTML("<h4><a href='{% url 'view_structure' structure.id %}' style='color: #177112'>{{ structure.name }}</a></h4>{% for internship in structure.internship_set.all %}<p><a href='{% url 'view_internship' internship.id %}' style='color: #23aa1b'>{{ internship.title }}</a></p>{% endfor %}")
            )
            .addTo(map);
    </script>
    {% endif %}
    {% endfor %}
    <script>
        new mapboxgl.Marker({ "color": "#ff0000" })
            .setLngLat(['{{internship.structure.location_lon}}', '{{internship.structure.location_lat}}'])
            .setPopup(
                new mapboxgl.Popup({ "anchor": "bottom-left" })
                    .setHTML("<h4><a href='{% url 'view_structure' internship.structure.id %}' style='color: #177112'>{{ internship.structure.name }}</a></h4>{% for internship in internship.structure.internship_set.all %}<p><a href='{% url 'view_internship' internship.id %}' style='color: #23aa1b'>{{ internship.title }}</a></p>{% endfor %}")
            )
            .addTo(map);
    </script>

    <style>
        .mapboxgl-popup-content{background-color: #c3e6c1;}
        .mapboxgl-popup-anchor-bottom-left > .mapboxgl-popup-tip { border-top-color: #c3e6c1;}
    </style>
    {% endif %}


{% endblock content %}

internshipproject/internshipapp/templates/internshipapp/view_structure.html
{% extends 'base.html' %}
{% block content %}

    <h2>STRUCTURE</h2>
    <h3>{{ structure_chosen.name }}</h3>
    
    <ul>
            <li>Ville - Pays : {{ structure_chosen.city }} - {{ structure_chosen.state }}</li>
            <li>Adresse : {{ structure_chosen.address }}</li>
        {% if structure_chosen.webpage %}
            <li>Lien : <a href="{{ structure_chosen.webpage }}">{{ structure_chosen.webpage }}</a></li>
        {% endif %}
        {% if structure_chosen.type %}
            <li>Type de structure_chosen : {{ structure_chosen.get_type_display }}</li>
        {% endif %}  
        {% if structure_chosen.contact %}
            <li>Contact (e-mail/téléphone) : {{ structure_chosen.contact }}</li>
        {% endif %}
        {% if structure_chosen.comment %}
            <li>Commentaire : {{ structure_chosen.comment }}</li>
        {% endif %}
    </ul>

    <a href="{% url 'edit_structure' structure_chosen.id %}">Modifier les infos de la structure</a>
    <a href="{% url 'delete_structure' structure_chosen.id %}">Supprimer la structure</a>

    <br><br><br>

    <!--_________MAP_________-->

    <!--Marker hover reactivity-->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script>
    <link href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css" rel="stylesheet" />
    <style>
        /* Change the cursor to a pointer on hover so the user knows it's clickable */
        .mapboxgl-marker:hover { cursor: pointer; }
        /* darken the marker on hover */
        .mapboxgl-marker:hover svg > g > g:nth-child(2) { fill: #6ea76b; }
    </style>

    <!--Display the map-->
    <div id='map' style='width: 40%; height: 40%;'></div>
    <script>
        mapboxgl.accessToken = '{{ mapbox_access_token }}';
        const map = new mapboxgl.Map({
            container: 'map', // container ID
            style: 'mapbox://styles/mapbox/streets-v11', // style URL
            center: ['{{structure_chosen.location_lon}}', '{{structure_chosen.location_lat}}'], // starting position [lng, lat]
            zoom: 5 // starting zoom
        });
        map.addControl(new mapboxgl.NavigationControl());
    </script>
    
    <!--Display markers on the map-->
    {% for structure in structures %}
    {% if structure != structure_chosen %}
    <script>
        new mapboxgl.Marker({ "color": "#23aa1b" })
            .setLngLat(['{{structure.location_lon}}', '{{structure.location_lat}}'])
            .setPopup(
                new mapboxgl.Popup({ "anchor": "bottom-left" })
                    .setHTML("<h4><a href='{% url 'view_structure' structure.id %}' style='color: #177112'>{{ structure.name }}</a></h4>{% for internship in structure.internship_set.all %}<p><a href='{% url 'view_internship' internship.id %}' style='color: #23aa1b'>{{ internship.title }}</a></p>{% endfor %}")
            )
            .addTo(map);
    </script>
    {% endif %}
    {% endfor %}
    <script>
        new mapboxgl.Marker({ "color": "#ff0000" })
            .setLngLat(['{{structure_chosen.location_lon}}', '{{structure_chosen.location_lat}}'])
            .setPopup(
                new mapboxgl.Popup({ "anchor": "bottom-left" })
                    .setHTML("<h4><a href='{% url 'view_structure' structure_chosen.id %}' style='color: #177112'>{{ structure_chosen.name }}</a></h4>{% for internship in structure_chosen.internship_set.all %}<p><a href='{% url 'view_internship' internship.id %}' style='color: #23aa1b'>{{ internship.title }}</a></p>{% endfor %}")
            )
            .addTo(map);
    </script>

    <style>
        .mapboxgl-popup-content{background-color: #c3e6c1;}
        .mapboxgl-popup-anchor-bottom-left > .mapboxgl-popup-tip { border-top-color: #c3e6c1;}
    </style>


    <br><br>

    <!--List of supervisors related to this structure-->
    {% if structure_chosen.supervisor_set.all %}
    <h3>Tuteurs·ices présents dans cette structure : </h3>
    <ul>
        {% for supervisor in structure_chosen.supervisor_set.all %}
        <li><a href="{% url 'view_supervisor' supervisor.id %}">{{ supervisor.name }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
    <br>

    <!--List of internships related to this structure-->
    {% if structure_chosen.internship_set.all %}
    <h3>Stages accessibles dans cette structure : </h3>
    <ul>
        {% for internship in structure_chosen.internship_set.all %}
        <li><a href="{% url 'view_internship' internship.id %}">{{ internship.title }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock content %}